[A Visual Intro to NumPy and Data Representation](https://jalammar.github.io/visual-numpy/)
<br>
grund syntax array np.array("liste")


### eindimensionale Arrays

In [1]:
import numpy as np

first_array = np.array([1,2,3])

In [2]:
first_array

array([1, 2, 3])

In [34]:
x = np.random.random(1)
x

array([0.78087479])

In [36]:
data = np.array([1,2])

ones = np.array([1,1])

In [37]:
sume = data + ones

In [44]:
sume + np.array([4,4])


array([6, 7])

In [47]:
x = np.random.random(5)
x

array([0.5054121 , 0.31545096, 0.47673512, 0.3626493 , 0.71497571])

Eine Aggregatfunktion ist eine Funktion, die gewisse Eigenschaften von Daten zusammenfasst

In [56]:
x = np.random.random(5)


x.min()
x.max()
x.sum()



1.1987150928331323

## 2d Arrays 

In [75]:
zweidemensionalarray = np.random.random((2,3))

zweidemensionalarray

eindimensional = np.ones((1))

In [90]:
zweidemensionalarray = np.random.random((2,2))

zweidemensionalarray

array([[0.33305827, 0.46867707],
       [0.33565928, 0.1901101 ]])

In [76]:
multy = zweidemensionalarray - eindimensional

In [79]:
x = multy.dot(zweidemensionalarray)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [86]:
# 2x3
zwei = np.random.random((1,3))

drei = np.random.random((3,1))
# 3x2

In [84]:
resultat = zwei.dot(drei)

In [85]:
resultat

array([[0.71352251]])

In [121]:
matrix = np.ones((4))

matrix.reshape(4,1)


array([[1.],
       [1.],
       [1.],
       [1.]])

In [110]:
matrix.max(axis=0)

array([0.65522471, 0.89855542, 0.10334708, 0.08651093, 0.54936296,
       0.54312847])

### n Dimensional Arrays

In [141]:
matrix = np.zeros((3,3,2))

matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])